[supervisord]
nodaemon=true
user=root
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid

[program:iventoy]
directory=/iventoy
environment=LD_LIBRARY_PATH="/iventoy/lib/lin64"
command=./lib/iventoy
autorestart=false
startsecs=0
startretries=0
